FROM scratch
COPY wasm/target/wasm32-wasi/release/wasm-inference.wasm /inference.wasm
COPY densenet201.tflite /
COPY sample.png /
COPY wasm/libtensorflowlite_c.so /
COPY wasm/libtensorflowlite_flex.so /
COPY wasm/libwasmedgePluginWasiNN.so /
CMD ["/inference.wasm"]
